[tool.poetry]
name = "utilities"
version = "0.1.0"
description = ""
authors = ["Niels P. Sorensen <niels.p.sorensen@softdesign.dk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
