[default]
log_level = "DEBUG"

SESSION_ID = "test_new"
MEMORY_URL = "redis://172.21.0.1:6379"
DATABASE_HOST = "172.21.0.1"
DATABASE_USERNAME = "postgres"
DATABASE_PASSWORD = "postgres"
DATABASE_TABLE = "TestVectors"
DATABASE_NAME = "vectors"
DATABASE_TYPE = "postgres"
EMBEDDINGS = "OpenAIEmbeddings"
SIMILARITY = 0.5
TOP_K = 4
DATABASE_PORT = 5432
