FROM mcr.microsoft.com/devcontainers/python:1-3.12-bullseye

## Pip dependencies
# Upgrade pip
RUN pip install --upgrade pip

# Install production dependencies

# Install development dependencies
# RUN pip install -r requirements-dev.txt